config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"
  # ゲストユーザー
  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'

  get 'about' => 'homes#about'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  #検索のため
  post '/search',  to: 'posts#search'
  get  '/search',  to: 'posts#search'

  resources :users, only: [:show, :edit, :update, :destroy] do
    member do
      get :likes
    end
    resource :follows, only: [:create, :destroy]
    get 'followings' => 'follows#followings', as: 'followings'
    get 'followers' => 'follows#followers', as: 'followers'
  end
  resources :genres, only: [:index, :edit, :create, :update, :destroy]

  resources :posts do
  resources :comments, only: [:create, :destroy]
  resource :likes, only: [:create, :destroy] # 単数形の`resource`にする
  get 'log', on: :collection
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true

  has_many :posts, dependent: :destroy
  belongs_to :user
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = current_user.genres
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.user_id = current_user.id
    if @genre.save
      redirect_to genres_path
    else
      flash.now[:alert] = 'ジャンル名を入力してください。'
      @genre = Genre.new
      @genres = current_user.genres
      render 'index'
    end
  end


  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])

    if @genre.update(genre_params)
      redirect_to genres_path
    else
      flash.now[:alert] = 'ジャンル名を入力してください。'
      render 'edit' # エラーがある場合、editに再表示
    end
  end


  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/edit.html.erb
<%= form_with(model: @genre, url: genre_path(@genre), method: :patch) do |f| %>
<div class="container ml-4 my-4">
  <h2><span class="bg-light p-2">ジャンル変更</span></h2>
  <div class="row mt-5">
    <div class="col-2">
      ジャンル名
    </div>

    <div class="col-2">
      <%= f.text_field :name, class:"form-control", placeholder:"ジャンル名" %>
    </div>

    <div class="col-2">
      <%= f.submit "変更を保存", class: "btn btn-success" %>
    </div>

  </div>
</div>

<% end %>

app/views/genres/index.html.erb
<!--ジャンル投稿-->
<%= form_with model: @genre, url: genres_path do |f| %>
<div class="container ml-4 my-4">
  <h2><span class="bg-light p-2">ジャンル一覧・追加</span></h2>
  <div class="row mt-5">
    <div class="col-2">
      ジャンル名
    </div>
    <div class="col-2">
      <%= f.text_field :name, class:"form-control", placeholder:"ジャンル名" %>
    </div>
    <div class="col-2">
      <%= f.submit "新規登録", class: "btn btn-success" %>
    </div>

    <% end %>


    <!--投稿一覧-->
  <div class="col-12 col-md-8">
    <table class="table mt-5">
      <thead>
       <tr>
        <th class="bg-light text-center ml-2">ジャンル</th>
        <th class="bg-light"></th>
        <th class="bg-light"></th>
       </tr>
      </thead>


      <tbody>
        <% @genres.each do |genre| %>
       　 <tr>
           <td><%= genre.name %></td>
       　   <td><%= link_to '編集する', edit_genre_path(genre), class: "btn btn-sm btn-success" %></td>
           <td><%= link_to "削除する", genre_path(genre), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger btn-sm" %></td>
         </tr>
         <% end %>
      </tbody>
    </table>
   </div>
  </div>
</div>