config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"
  # ゲストユーザー
  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'

  get 'about' => 'homes#about'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  #検索のため
  post '/search',  to: 'posts#search'
  get  '/search',  to: 'posts#search'

  resources :users, only: [:show, :edit, :update, :destroy] do
    member do
      get :likes
    end
    resource :follows, only: [:create, :destroy]
    get 'followings' => 'follows#followings', as: 'followings'
    get 'followers' => 'follows#followers', as: 'followers'
  end
  resources :genres, only: [:index, :edit, :create, :update, :destroy]

  resources :posts do
  resources :comments, only: [:create, :destroy]
  resource :likes, only: [:create, :destroy] # 単数形の`resource`にする
  get 'log', on: :collection
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :profile_image

  validates :name, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :genres, dependent: :destroy

  # フォローをした、されたの関係
  has_many :follows, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_follows, class_name: "Follow", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :follows, source: :followed
  has_many :followers, through: :reverse_of_follows, source: :follower

  has_many :posts, :dependent => :destroy
  # 退会ユーザーに紐づくお気に入りも削除する場合
  has_many :likes, :dependent => :destroy
  # 退会ユーザーに紐づくコメントも削除する場合
  has_many :comments, :dependent => :destroy
  # 退会でゲストは退会できないようにする
  def guest?
    self.email == "guest@gmail.com"
  end

  # プロフィール画像がない場合no_image.jpgを表示
  def get_profile_image
    if profile_image.attached?
      image
    else
      'no_image.jpg'
    end
  end

   # フォローしたときの処理
  def follow(user_id)
    follows.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    follows.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

end

app/controllers/users/registrations_controller.rb
# ゲストユーザーを削除できないようにする

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: :destroy

  def ensure_normal_user
    if resource.email == 'guest@gmail.com'
      redirect_to root_path, alert: 'ゲストユーザーは削除できません。'
    end
  end

  def create
    ActiveRecord::Base.transaction do
      super
      if resource.persisted?
        Genre.create(name: "胸トレ", user_id: current_user.id)
        Genre.create(name: "背中トレ", user_id: current_user.id)
        Genre.create(name: "足トレ", user_id: current_user.id)
        Genre.create(name: "肩トレ", user_id: current_user.id)
        Genre.create(name: "その他", user_id: current_user.id)
      else
         # ユーザーの新規登録が失敗した場合
        clean_up_passwords resource
        set_minimum_password_length
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:likes, :show, :comments, :destroy]

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to user_path
    else
      flash.now[:alert] = 'ユーザーネームを入力してください。'
      @user = User.find(params[:id])
      render 'edit' # エラーがある場合、editに再表示
    end
  end

  def likes
    @user = User.find(params[:id])
    likes = Like.where(user_id: @user.id).pluck(:post_id)
    @like_posts = Post.find(likes)
  end

  def destroy
    @users = User.all
    @user.destroy
    flash[:notice] = 'ユーザーを削除しました。'
    redirect_back(fallback_location: root_path)
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:profile_image, :name, :goal)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<style>
   .with-border {
     border: 2px solid #dee2e6;
  }
</style>
<%= form_with model: @user do |f| %>

<div class="container" style="margin-top: 40px;">
  <div class="row justify-content-center">

    <div class="col-md-9">

        <div class="form-group row">
          <div class="col-md-4">
            <% if @user.profile_image.present? %>
              <%= image_tag @user.profile_image, class: "rounded-circle profile-image with-border", width: "150", height: "150" %>
            <% else %>
              <%= image_tag 'no_image.jpg', class: "rounded-circle profile-image with-border", width: "150", height: "150" %>
            <% end %>
            </div>
          <div class="col-md-8">
            <%= f.file_field :profile_image, accept: "image/*" %>
          </div>
        </div>



      　<div class="form-group row">
          <div class="col-md-4">
            <%= f.label :（ユーザーネーム）, class: "col-form-label" %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
　　　　</div>

        <div class="form-group row">
          <div class="col-md-5">
            <%= f.label :（目標）, class: "col-form-label" %>
            <%= f.text_area :goal, class: "form-control" %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-md-7 text-right">
            <%= f.submit "編集内容を保存", class: "btn btn-success" %>
          </div>
        </div>

    </div>
  </div>
</div>

<% end %>

app/views/users/likes.html.erb
<div class="container">
  <h2 class="text-center"><span class="bg-light">いいねした記録</span></h2>
  <div class="row justify-content-center">
   <% @like_posts.each do |post|%>
     <div class="col-md-7 mb-4">
      <%= link_to post_path(post) do %>
        <div class="card">
          <div class="card-header d-flex align-items-center">
            <!-- プロフィール画像 -->
            <% if post.user.present? && post.user.profile_image.attached? %>
              <%= image_tag post.user.profile_image, class: "rounded-circle profile-image", width: "50", height: "50" %>
            <% else %>
              <%= image_tag 'no_image.jpg', class: "rounded-circle profile-image", width: "50", height: "50" %>
            <% end %>

            <!-- ユーザー名 -->
            <h5 class="card-title mx-5"><%= link_to post.user.name, user_path(post.user) %></h5>
          </div>

          <div class="card-body">
            <!-- 投稿内容 -->
            <!--simple_formatで改行を導入-->
            <h5 class="card-title">・<%= post.genre.name %></h5>
            <p class="card-text"><%= simple_format(post.body) %></p>
            <span class="sentiment-score text-muted">本文の感情分析スコア(-1.0~1.0) <%= post.score %></span>
            <p class="text-muted">投稿日時:<%= post.created_at.strftime("%Y年%m月%d日 %H時%M分") %></p>

            <!-- 投稿画像 -->
            <% if post.image.attached? %>
              <%= image_tag post.image.variant(resize: "300x200"), class: "img-fluid" %>
            <% end %>
          </div>

          <div class="card-footer">
            <!-- コメントボタン -->
            <%= link_to post_path(post), class: "btn btn-primary btn-sm mr-2" do %>
             <i class='far fa-comment-alt'></i>　コメントする！
            <% end %>

            <!-- いいね（お気に入り）ボタン -->
            <div id="like_buttons_<%= post.id %>" class="d-inline">
              <%= render "likes/like", post: post %>
            </div>
          </div>
        </div>
       <% end %>
     </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<style>
  .table {
    width: 100%;
    table-layout: fixed;
  }
  .table th,
  .table td {
    padding: 10px;
    text-align: left;
    vertical-align: middle;
  }
  .table h6 {
    margin: 0;
  }
  .with-border {
     border: 2px solid #dee2e6;
  }
</style>
<div class="container">
  <div class="row align-items-start">
    <div class="col-4">
      <div class="user-profile text-center">
        <div class="profile-header">
          <% if @user.profile_image.present? %>
            <%= image_tag @user.profile_image, class: "rounded-circle profile-image with-border", width: "150", height: "150" %>
          <% else %>
            <%= image_tag 'no_image.jpg', class: "rounded-circle profile-image with-border", width: "150", height: "150" %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-7">
      <div class="border" style="padding:10px;">
        <table class='table'>
　　　　　 <tr>
        	  <th class="col-3">名前</th>
        	  <th><%= @user.name %></th>
          </tr>
          <tr>
        	  <th>目標</th>
        	  <th style="height: 100px;"><%= @user.goal %></th>
          </tr>
          <tr>
            <th>フォロー</th>
            <th>
              <%= link_to user_followings_path(@user) do %>
                <h6><%= @user.followings.count %></h6>
              <% end %>
            </th>
          </tr>
          <tr>
            <th>フォロワー</th>
            <th>
              <%= link_to user_followers_path(@user) do %>
                <h6><%= @user.followers.count %></h6>
              <% end %>
            </th>
          </tr>
        </table>

        <% if current_user == @user %>
          <%= link_to 'プロフィールを編集する', edit_user_path(@user), class: "btn btn-primary btn-sm" %>
          <%= link_to "いいねした記録", likes_user_path(@user), class: "btn btn-success btn-sm" %>

        <% else %>
          <!-- フォロー機能 -->
          <% if current_user.following?(@user) %>
            <%= link_to "フォロー外す", user_follows_path(@user.id), method: :delete, class: "btn btn-success btn-sm" %>
          <% else %>
            <%= link_to "フォローする", user_follows_path(@user.id), method: :post, class: "btn btn-primary btn-sm" %>
          <% end %>
        <% end %>
      </div>
　   </div>
  </div>
    <% if user_signed_in? %>
      <% if current_user.admin? %>
      <h4>登録ユーザー数</h4>
        <div class="table-responsive">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>メールアドレス</th>
                <th>名前</th>
                <th>退会処理</th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |u| %>
                <tr>
                  <td><%= u.email %></td>
                  <td><%= u.name %></td>
                  <% unless u.guest? || u.admin? %>
                    <td><%= link_to "退会させる",user_path(u), class: "destroy-user btn btn-danger", method: :delete, "data-confirm" => "本当に退会させますか？" %></td>
                  <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <p>登録者合計：<%= @users.count %></p>
      <% end %>
    <% end %>
</div>