config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"
  # ゲストユーザー
  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'

  get 'about' => 'homes#about'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  #検索のため
  post '/search',  to: 'posts#search'
  get  '/search',  to: 'posts#search'

  resources :users, only: [:show, :edit, :update, :destroy] do
    member do
      get :likes
    end
    resource :follows, only: [:create, :destroy]
    get 'followings' => 'follows#followings', as: 'followings'
    get 'followers' => 'follows#followers', as: 'followers'
  end
  resources :genres, only: [:index, :edit, :create, :update, :destroy]

  resources :posts do
  resources :comments, only: [:create, :destroy]
  resource :likes, only: [:create, :destroy] # 単数形の`resource`にする
  get 'log', on: :collection
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/post.rb
class Post < ApplicationRecord
  validates :genre_id, presence: true
  validates :body, presence: true

  has_one_attached :image

  belongs_to :user
  belongs_to :genre

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  # bodyカラムを検索する
  def self.search(search)
    return Post.all unless search
     Post.joins(:genre).where('posts.body LIKE(?) OR genres.name LIKE(?)', "%#{search}%", "%#{search}%")
  end

  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.score = Language.get_data(post_params[:body])
    if @post.save
      redirect_to posts_path
    else
      flash.now[:alert] = '記録に失敗しました。'
      render 'new'
    end
  end

  def index
    @posts = Post.all
    @users = User.all
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comment = Comment.new
  end

  def edit
    @post = Post.find(params[:id])
    @user = @post.user
  end

  def log
    user_id = current_user.id
    @posts = Post.where(user_id: user_id)
  end

  # 検索のためのコントローラー
  def search
    @keyword = params[:post][:search] if params[:post]
    @posts_all = Post.search(@keyword)
    @posts = @posts_all
  end

  def update
    @post = Post.find(params[:id])
    @post.score = Language.get_data(post_params[:body])
    if @post.update(post_params)
       redirect_to posts_path
    else
      flash.now[:alert] = '記録の変更ができませんでした。'
      @post = Post.find(params[:id])
      render 'edit' # エラーがある場合、editに再表示
    end

  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:genre_id, :body, :start_time, :image)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div class="container">
  <div class="row justify-content-center">
    <% @posts.order(created_at: :desc).each do |post| %>
     <div class="col-md-7 mb-4">
      <%= link_to post_path(post) do %>
        <div class="card">
          <div class="card-header d-flex align-items-center">
            <!-- プロフィール画像 -->
            <% if post.user.present? && post.user.profile_image.attached? %>
              <%= image_tag post.user.profile_image, class: "rounded-circle profile-image", width: "50", height: "50" %>
            <% else %>
              <%= image_tag 'no_image.jpg', class: "rounded-circle profile-image", width: "50", height: "50" %>
            <% end %>

            <!-- ユーザー名 -->
            <h5 class="card-title mx-5"><%= link_to post.user.name, user_path(post.user) %></h5>
          </div>

          <div class="card-body">
            <!-- 投稿内容 -->
            <!--simple_formatで改行を導入-->
            <h5 class="card-title">・<%= post.genre.name %></h5>
            <p class="card-text"><%= simple_format(post.body) %></p>
            <p class="sentiment-score text-muted">本文の感情分析スコア(-1.0~1.0) <%= post.score %></p>
            <!-- 投稿画像 -->
            <% if post.image.attached? %>
              <%= image_tag post.image.variant(resize: "300x200"), class: "img-fluid" %>
            <% end %>
            <p class="text-muted">投稿日時:<%= post.created_at.strftime("%Y年%m月%d日 %H時%M分") %></p>
          </div>

          <div class="card-footer">
            <!-- コメントボタン -->
            <%= link_to post_path(post), class: "btn btn-primary btn-sm mr-2" do %>
             <i class='far fa-comment-alt'></i>　コメントする！
            <% end %>

            <!-- いいね（お気に入り）ボタン -->
            <div id="like_buttons_<%= post.id %>" class="d-inline">
              <%= render "likes/like", post: post %>
            </div>
          </div>
        </div>
       <% end %>
     </div>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2>記録編集</h2>

  　　　<%= form_with model: @post do |f| %>
        <div class="time">
          <%= f.label :start_time %>
          <%= f.datetime_select :start_time %>
        </div>

        <div class="name">
          <%= f.label :ジャンル %>
          <%= f.collection_select :genre_id, current_user.genres, :id, :name, include_blank: "-- 選択してください --" %>
        </div>

        <div class="body">
          <%= f.label :内容 %>
          <%= f.text_area :body, class: "form-control" %>
        </div>


        <div class="image">
          <%= f.label :画像 %>
          <%= f.file_field :image, accept: "image/*" %>
        </div>

        <div class="actions">
          <%= f.submit "変更を保存", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<%= render 'post', posts: @posts %>

app/views/posts/log.html.erb
<div class="container">
  <!--カレンダー機能-->
  <%= month_calendar events: @posts do |date, posts| %>
    <%= date.day %>
      <% posts.each do |post| %>
        <div>
          <%= link_to post.genre.name, post_path(post), class: "btn btn-danger btn-sm my-1 btn-block" %>
        </div>
      <% end %>
  <% end %>

  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>

      <div class="btn-wrapper col-10 mx-auto">


        <div class="row">
          <%= link_to '本日のトレーニングの追加',new_post_path, class: "btn btn-info btn-sm btn-block mb-3" %>
        </div>

        <div class="row">
          <%= link_to 'ジャンルの追加',genres_path, class: "btn btn-success btn-sm btn-block" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2>記録を入力</h2>

  　　　<%= form_with(model: @post, local: true) do |f| %>
        <div class="time">
          <%= f.label :時間 %>
          <%= f.datetime_select :start_time %>
        </div>

        <div class="name">
          <%= f.label :ジャンル %>
          <%= f.collection_select :genre_id, current_user.genres, :id, :name, include_blank: "-- 選択してください --" %>
        </div>

        <div class="body">
          <%= f.label :内容 %>
          <%= f.text_area :body, class: "form-control" %>
        </div>


        <div class="image">
          <%= f.label :画像 %>
          <%= f.file_field :image, accept: "image/*" %>
        </div>

        <div class="actions">
          <%= f.submit "記録する", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/search.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col">
      <h3>検索結果</h3>
      <p>
        検索キーワード: "<%= @keyword %>"  <br>
        一致した投稿: <%= @posts_all.count  %>
      </p>
      <ul class="posts">
         <%= render 'post', posts: @posts %>
      </ul>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<!-- 投稿詳細 -->
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-7 mb-4">
      <div class="card">
        <div class="card-header d-flex align-items-center">
          <!-- プロフィール画像 -->
          <% if @post.user.present? && @post.user.profile_image.attached? %>
            <%= image_tag @post.user.profile_image, class: "rounded-circle profile-image", width: "50", height: "50" %>
          <% else %>
            <%= image_tag 'no_image.jpg', class: "rounded-circle profile-image", width: "50", height: "50" %>
          <% end %>

          <!-- ユーザー名 -->
          <h5 class="card-title mx-5"><%= link_to @post.user.name, user_path(@post.user) %></h5>
          <!-- 編集と削除ボタン -->
          <% if user_signed_in? %>
            <% if @post.user == current_user %>
              <div class="text-center my-3">
                <%= link_to '編集する', edit_post_path(@post), class: "btn btn-sm btn-success mx-2" %>
                <%= link_to "削除する", post_path(@post), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger btn-sm mx-2" %>
              </div>
            <% elsif current_user.admin? %>
              <div class="text-center my-3">
                <%= link_to '管理者編集', edit_post_path(@post), class: "btn btn-sm btn-success mx-2" %>
                <%= link_to "管理者削除", post_path(@post), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger btn-sm mx-2" %>
              </div>
            <% end %>
          <% end %>
          </div>

        <div class="card-body">
          <!-- 投稿内容 -->
          <!--simple_formatで改行を導入-->
          <h5 class="card-title">・<%= @post.genre.name %></h5>
          <p class="card-text"><%= simple_format(@post.body) %></p>
          <span class="sentiment-score text-muted">本文の感情分析スコア(-1.0~1.0) <%= @post.score %></span>
          <p class="text-muted">投稿日時:<%= @post.created_at.strftime("%Y年%m月%d日 %H時%M分") %></p>

          <!-- 投稿画像 -->
          <% if @post.image.attached? %>
            <%= image_tag @post.image.variant(resize: "300x200"), class: "img-fluid" %>
          <% end %>
        </div>

        <div class="card-footer">
          <div class="item" style="display: flex;">
            <!-- コメント数 -->
            <div id="comment_counter">
              <%= render "comments/counter", post: @post %>
            </div>
            <!-- いいね（お気に入り）ボタン -->
            <div id="like_buttons_<%= @post.id %>" class="d-inline ml-3">
              <%= render "likes/like", post: @post %>
            </div>
          </div>
          <!-- コメントの表示 -->
          <div id="comment_index">
            <%= render "comments/index", post: @post %>
          </div>

          <!-- コメントフォーム -->
          <div class="comment-form mt-3">
            <%= render "comments/form", post: @post, comment: @comment %>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>