config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"
  # ゲストユーザー
  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'

  get 'about' => 'homes#about'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  #検索のため
  post '/search',  to: 'posts#search'
  get  '/search',  to: 'posts#search'

  resources :users, only: [:show, :edit, :update, :destroy] do
    member do
      get :likes
    end
    resource :follows, only: [:create, :destroy]
    get 'followings' => 'follows#followings', as: 'followings'
    get 'followers' => 'follows#followers', as: 'followers'
  end
  resources :genres, only: [:index, :edit, :create, :update, :destroy]

  resources :posts do
  resources :comments, only: [:create, :destroy]
  resource :likes, only: [:create, :destroy] # 単数形の`resource`にする
  get 'log', on: :collection
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/follow.rb
class Follow < ApplicationRecord
  # １人のユーザーはたくさんのユーザーをフォローできる
  belongs_to :follower, class_name: "User"
  # １人のユーザーはたくさんのユーザーにフォローされる
  belongs_to :followed, class_name: "User"
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true

  has_many :posts, dependent: :destroy
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :genre_id, presence: true
  validates :body, presence: true

  has_one_attached :image

  belongs_to :user
  belongs_to :genre

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  # bodyカラムを検索する
  def self.search(search)
    return Post.all unless search
     Post.joins(:genre).where('posts.body LIKE(?) OR genres.name LIKE(?)', "%#{search}%", "%#{search}%")
  end

  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :profile_image

  validates :name, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :genres, dependent: :destroy

  # フォローをした、されたの関係
  has_many :follows, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_follows, class_name: "Follow", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :follows, source: :followed
  has_many :followers, through: :reverse_of_follows, source: :follower

  has_many :posts, :dependent => :destroy
  # 退会ユーザーに紐づくお気に入りも削除する場合
  has_many :likes, :dependent => :destroy
  # 退会ユーザーに紐づくコメントも削除する場合
  has_many :comments, :dependent => :destroy
  # 退会でゲストは退会できないようにする
  def guest?
    self.email == "guest@gmail.com"
  end

  # プロフィール画像がない場合no_image.jpgを表示
  def get_profile_image
    if profile_image.attached?
      image
    else
      'no_image.jpg'
    end
  end

   # フォローしたときの処理
  def follow(user_id)
    follows.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    follows.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = current_user.genres
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.user_id = current_user.id
    if @genre.save
      redirect_to genres_path
    else
      flash.now[:alert] = 'ジャンル名を入力してください。'
      @genre = Genre.new
      @genres = current_user.genres
      render 'index'
    end
  end


  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])

    if @genre.update(genre_params)
      redirect_to genres_path
    else
      flash.now[:alert] = 'ジャンル名を入力してください。'
      render 'edit' # エラーがある場合、editに再表示
    end
  end


  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_action :authenticate_user!

  def top
  end

  def about
  end

  # ゲストログイン
  def guest_sign_in
    user = User.find_or_create_by!(email: 'guest@gmail.com') do |user|
      user.name = 'ゲスト'
      user.password = SecureRandom.urlsafe_base64
    end
    sign_in user
    redirect_to log_posts_path
  end



end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    like = current_user.likes.new(post_id: @post.id)
    like.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    like = current_user.likes.find_by(post_id: @post.id)
    like.destroy
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.score = Language.get_data(post_params[:body])
    if @post.save
      redirect_to posts_path
    else
      flash.now[:alert] = '記録に失敗しました。'
      render 'new'
    end
  end

  def index
    @posts = Post.all
    @users = User.all
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comment = Comment.new
  end

  def edit
    @post = Post.find(params[:id])
    @user = @post.user
  end

  def log
    user_id = current_user.id
    @posts = Post.where(user_id: user_id)
  end

  # 検索のためのコントローラー
  def search
    @keyword = params[:post][:search] if params[:post]
    @posts_all = Post.search(@keyword)
    @posts = @posts_all
  end

  def update
    @post = Post.find(params[:id])
    @post.score = Language.get_data(post_params[:body])
    if @post.update(post_params)
       redirect_to posts_path
    else
      flash.now[:alert] = '記録の変更ができませんでした。'
      @post = Post.find(params[:id])
      render 'edit' # エラーがある場合、editに再表示
    end

  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:genre_id, :body, :start_time, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:likes, :show, :comments, :destroy]

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to user_path
    else
      flash.now[:alert] = 'ユーザーネームを入力してください。'
      @user = User.find(params[:id])
      render 'edit' # エラーがある場合、editに再表示
    end
  end

  def likes
    @user = User.find(params[:id])
    likes = Like.where(user_id: @user.id).pluck(:post_id)
    @like_posts = Post.find(likes)
  end

  def destroy
    @users = User.all
    @user.destroy
    flash[:notice] = 'ユーザーを削除しました。'
    redirect_back(fallback_location: root_path)
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:profile_image, :name, :goal)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Training</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/52ec04519a.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <style>
  header {
    margin-bottom: 50px;
  }
　</style>


  <body>
    <header>
     <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="/">
          <span><img src="<%= asset_path('rogo3.png') %>" alt="ロゴ" style="width: 80px; max-height: 80px; object-fit: contain;"></span>
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="search">
                <%= form_with(url: search_path, scope: :post, local: true) do |f| %>
                  <%= f.text_field :search, placeholder: "キーワード検索" %>
                  <% f.submit %>
                <% end %>
              </li>
              <!--管理者-->
              <% if current_user.admin? %>
                <li>
                  <%= link_to "管理者マイページ", user_path(current_user.id), class: "btn" %>
                </li>
                <li>
                  <%= link_to "みんなの記録", posts_path, class: "btn" %>
                </li>

              <!--ユーザー-->
              <% else %>
                <li>
                  <%= link_to "マイページ", user_path(current_user.id), class: "btn" %>
                </li>
                <li>
                  <%= link_to "記録する", log_posts_path, class: "btn" %>
                </li>
                <li>
                  <%= link_to "みんなの記録", posts_path, class: "btn" %>
                </li>
              <% end %>
              <li>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn" %>
              </li>
            <!--ログイン前-->
            <% else %>
              <li>
                <%= link_to "About", about_path, class: "btn" %>
              </li>
              <li>
                <%= link_to "新規登録", new_user_registration_path, class: "btn" %>
              </li>
              <li>
                <%= link_to "ログイン", new_user_session_path, class: "btn" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </header>
    <!--エラーメッセージ-->
      <% if flash[:alert].present? %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>
    <%= yield %>
      <footer>
        <div>
        	<div class="container">
        		<div class="row justify-content-center">
             © Let’s Training
            </div>
            <ul class="navbar-nav ml-auto">
                <div class="row justify-content-center">
                  <a href="#" class="mr-4"><i class="fab fa-facebook-f fa-lg"></i></a>
                  <a href="#" class="mr-4"><i class="fa-brands fa-x-twitter fa-lg"></i></a>
                  <a href="#" class="mr-4"><i class="fab fa-google-plus-g fa-lg"></i></a>
                  <a href="#" class="mr-4"><i class="fab fa-instagram fa-lg"></i></a>
                  <a href="#" ><i class="fa-brands fa-threads fa-lg"></i></i></a>
                </div>
            </ul>

        	</div>
        </div>
      </footer>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '＜'), calendar.url_for_previous_view %>
    <span class="calendar-title" style="font-size: 20px;"><%= start_date.year %>年 <%= t('date.month_names')[start_date.month] %></span>
    <%= link_to t('simple_calendar.next', default: '＞'), calendar.url_for_next_view %>
  </div>

  <table class="calendar-table table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>